### ISSUE TITLE
Feilmelding med Home Assistant 2022.3.0

### ISSUE THREAD

**Issue by svhelge** [Olen/home-assistant-skisporet#2]
Etter å ha oppgradert HA til 2022.3.0 får jeg følgende feilmelding ved "Check configuration":
   Platform error sensor.skisporet - Requirements for skisporet not found: ['pandas==1.2.3']

Fra log:
`
2022-03-03 21:20:18 INFO (SyncWorker_2) [homeassistant.util.package] Attempting install of pandas==1.2.3
2022-03-03 21:20:21 INFO (MainThread) [custom_components.hpprinter.api.HPPrinterAPI] Cannot retrieve data (ConsumableConfigDyn) from printer, Error: , Line: 136
2022-03-03 21:20:29 ERROR (SyncWorker_2) [homeassistant.util.package] Unable to install package pandas==1.2.3: error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [54 lines of output]
Traceback (most recent call last):
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 23, in <module>
from . import multiarray
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/core/multiarray.py", line 10, in <module>
from . import overrides
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/core/overrides.py", line 6, in <module>
from numpy.core._multiarray_umath import (
ImportError: Error loading shared library /tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so: Operation not permitted
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
main()
File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
return hook(config_settings)
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
return self._get_build_requires(
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
self.run_setup()
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
super(_BuildMetaLegacyBackend,
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
exec(compile(code, __file__, 'exec'), locals())
File "setup.py", line 20, in <module>
import numpy
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 144, in <module>
from . import core
File "/tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/core/__init__.py", line 49, in <module>
raise ImportError(msg)
ImportError:
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
* The Python version is: Python3.9 from "/usr/local/bin/python3"
* The NumPy version is: "1.22.0"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: Error loading shared library /tmp/pip-build-env-iyylo_dw/overlay/lib/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-x86_64-linux-gnu.so: Operation not permitted
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
2022-03-03 21:20:29 INFO (SyncWorker_7) [homeassistant.util.package] Attempting install of pandas==1.2.3`

**Comment by svhelge** [comment]
Solved with #3
